// <auto-generated />
namespace OAuthMvc4Guide.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddExtraUserInformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExtraUserInformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201306250403473_AddExtraUserInformation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
